#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
#          uri:
#            lb://first-service/   # advantage of using load balance that no need to explicity remember host & port
#          #uri: http://localhost:8083/
#          predicates:
#            - Path=/api/v1/**
#        - id: second-service
#          uri:
#            lb://second-service/
#          #uri: http://localhost:8084/
#          predicates:
#            - Path=/api/v2/**