FROM openjdk:8-jdk-alpine
LABEL authors="MADHUBALA"
#RUN apk update && apk upgrade
#ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
#ENV PATH $PATH: $JAVA_HOME/bin
#RUN mkdir -p /target
#RUN mkdir -p /CloudGatewayService
#COPY ./target/*.jar /CloudGatewayService/
#RUN mkdir -p src/main/resources
#COPY ./src/main/resources /src/main/resources
RUN mkdir -p src/main/resources
ADD ./src/main/resources /src/main/resources
ADD ./target/*.jar /app.jar

#USER root
#RUN chown -R 1001:1001 /src/main/resources
#RUN chmod -R 777 /src/main/resources


EXPOSE 8080
ENTRYPOINT [ "sh", "-c", "java -jar  app.jar" ]
#ENTRYPOINT /bin/sh -c "java -jar  \$JAVA_OPTS /CloudGatewayServiceapp/CloudGatewayService-0.0.1-SNAPSHOT.jar -"